// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using garbage_collection.Data;

#nullable disable

namespace garbage_collection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250319153111_UpdateCollections")]
    partial class UpdateCollections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");
#pragma warning restore 612, 618
        }
    }
}
