// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using garbage_collection.Data;

#nullable disable

namespace garbage_collection.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250409163316_AddCitizenTable")]
    partial class AddCitizenTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("garbage_collection.Models.CollectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bin_id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Collection_time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("collections");
                });
#pragma warning restore 612, 618
        }
    }
}
